SELECT CKY_CNT_CLFR, CKY_ART, max(date) FROM (
    SELECT CKY_CNT_CLFR, CKY_ART, concat('2017 ', DTT_SCAD) date FROM `dbmirror`.`MM_RIGHE` WHERE CSG_DOC = 'BF'
    UNION
    SELECT CKY_CNT_CLFR, CKY_ART, concat('2016 ', DTT_SCAD) date FROM `dbmirror16`.`MM_RIGHE` WHERE CSG_DOC = 'BF' 
    UNION
    SELECT CKY_CNT_CLFR, CKY_ART, concat('2015 ', DTT_SCAD) date FROM `dbmirror15`.`MM_RIGHE` WHERE CSG_DOC = 'BF'
    UNION
    SELECT CKY_CNT_CLFR, CKY_ART, concat('2014 ', DTT_SCAD) date FROM `dbmirror14`.`MM_RIGHE` WHERE CSG_DOC = 'BF'
    UNION
    SELECT CKY_CNT_CLFR, CKY_ART, concat('2013 ', DTT_SCAD) date FROM `dbmirror13`.`MM_RIGHE` WHERE CSG_DOC = 'BF'
    ) totale
GROUP BY CKY_ART, CKY_CNT_CLFR
ORDER BY CKY_ART, max(date) DESC;
